### PR TITLE
fix(den): count OAuth normalization failures

### PR DESCRIPTION
**Pull request by reachjalil**
## Summary

- record OAuth token normalization `400 invalid_target` responses before returning
- make those pre-handler failures consume the 15-per-5-minute failure budget introduced by #3941
- add a focused regression witness and testkit assertion for the blocked 16th request

This is intentionally stacked on #3941 and contains only the unresolved normalization-failure follow-up.

## Verification

Passed locally on commit `fcc5668a705277ffe891020962a5f993ff8df586`:

- `pnpm --dir ee/apps/den-api exec bun test test/oauth-token-rate-limit.test.ts` — 5 passed
- `pnpm --filter @openwork/mcp-apps build`
- `pnpm --dir ee/apps/den-api exec tsc --noEmit --pretty false`
- `pnpm evals:pr specs/oauth-token-rate-limit.test.ts` — 1 passed, 0 skipped

## Proof status

**Incomplete** — the local testkit tape passes, but Daytona credentials are unavailable in this session, so no remote exact-head tape has been published. The PR remains draft.

A broader existing normalization suite was also attempted and fails during Better Auth initialization because its DB test double does not implement `db.insert`; that failure occurs before the assertions touched by this patch.

### CODE REVIEW

**Comment by reachjalil** [comment]
Closing as superseded by 9decac0d7 in #3941. Ben’s new commit records the same pre-handler token normalization rejections against the failure budget and adds the corresponding five-test witness, resolving the Warden thread. Keeping this draft’s branch intact for traceability.
