### ISSUE TITLE
[Bug]: Windows: hard `throw` in getComputerUseMcpCommand() crashes desktop renderer (blank screen) on 0.17.30 and 0.17.32

### ISSUE THREAD

**Issue by LellesBodega** [different-ai/openwork#2908]
### Summary

**Environment**
- OS: Windows 11
- OpenWork versions tested: 0.17.30, 0.17.32 (both affected identically)
- Install path: %LOCALAPPDATA%\Programs\@openworkdesktop\
- Config: %APPDATA%\openwork\, ~/.config/opencode/opencode.json

**Symptom**
App window goes blank/unresponsive on startup (or when opening Settings, depending on build). No log files are written by default; running the .exe from a terminal surfaces:

    Error: OpenWork Computer Use is missing from this OpenWork build.

**Root cause (confirmed via app.asar extraction)**
In `server/dist/extensions/google-workspace.js`:

    function computerUseHelperAppPath() {
      const explicitApp = process.env.OPENWORK_COMPUTER_USE_APP?.trim();
      const candidates = [
        explicitApp,
        process.resourcesPath ? path.join(process.resourcesPath, "helpers", COMPUTER_USE_HELPER_APP_NAME) : null,
        path.resolve(__dirname, "..", "resources", "helpers", COMPUTER_USE_HELPER_APP_NAME),
      ].filter(Boolean);
      return candidates.find((candidate) => existsSync(candidate)) ?? null;
    }

    function getComputerUseMcpCommand() {
      const helperExecutable = computerUseHelperExecutablePath();
      if (helperExecutable) return [helperExecutable, "mcp"];
      if (app.isPackaged) {
        throw new Error("OpenWork Computer Use is missing from this OpenWork build.");
      }
      ...
    }

`COMPUTER_USE_HELPER_APP_NAME = "OpenWork Computer Use.app"` and the executable path is built as `Contents/MacOS/ComputerUse` — this is exclusively a macOS `.app` bundle structure. There is no `win32` branch anywhere in `computerUseHelperAppPath()`/`computerUseHelperExecutablePath()` that resolves a Windows helper path or binary (confirmed — the file has many other `process.platform === "win32"` branches for unrelated concerns like shell selection and auto-update assets, but none for this lookup). So on Windows, `helperExecutable` is always `null`, `app.isPackaged` is `true` for an installed build, and the function throws unconditionally.

This is invoked via IPC channel `getComputerUseMcpCommand` (registered in `server/dist/extensions/openai-image-generation.js`), with no `try/catch` around the call in either file. If the renderer calls this channel during initial mount (e.g. to enumerate available MCP tools) without handling the rejection, the result is an uncaught error that blanks the window.

**Suggested fix**
Return `null` instead of throwing when the helper is unavailable on non-macOS platforms, and have the caller treat `null` as "Computer Use unavailable" rather than propagating an exception. Ideally, gate the whole Computer Use extension registration behind `process.platform === "darwin"` until Windows/Linux support exists, so it never appears as an available tool on unsupported platforms in the first place.

**Confirmed via**: extracting app.asar from the installed build and locating the throw site directly (see code above).

### To Reproduce

**Repro steps**
1. Install OpenWork on Windows (0.17.30 or 0.17.32).
2. Launch normally, or open Settings.
3. Window goes blank / unresponsive.
4. Run the .exe from cmd.exe to see the thrown error in stdout.

### Expected behavior

Window going blank / unresponsive.

### Actual behavior

Window goes blank / unresponsive.

**Comment by LellesBodega** [comment]
Description:
Opening the "Settings" view while the application is running (or when Computer Use permissions are missing) causes a White Screen of Death (WSOD). The application completely crashes and requires a restart.

Upon debugging and unpacking the app.asar, I found that this is caused by a chain reaction of two separate bugs: an unhandled exception in the backend, followed by a TypeError in the React frontend.

Steps to Reproduce:
Disconnect the computer from the internet (or start the app in a state where Computer Use is disabled/unavailable).
Open the OpenWork Desktop app.
Click on "Settings".
The screen turns completely white.

Root Cause Analysis:
1. Backend Error (electron/computer-use.mjs)
When the app is offline or missing Computer Use dependencies, computer-use.mjs throws a hardcoded error instead of gracefully returning a disabled state or fallback object.

Behavior: This unhandled error breaks the initial fetch sequence when the settings page tries to load the MCP configurations.

2. Frontend React Crash (TypeError: as.config.command?.some is not a function)
Even if the backend provides a valid MCP server object (or a dummy object to bypass the first bug), the frontend instantly crashes when trying to render the settings view.

Behavior: In the frontend code, there is a check looking for the Chrome DevTools extension that looks something like this:
as.config.command?.some(_i => _i.includes("chrome-devtools"))

The Bug: The command property on an MCP server configuration is a string (e.g., "node", "npx", "echo"). Since it is a string and not an array, the .some() method does not exist, triggering a fatal TypeError that crashes the entire React tree.

Proposed Fixes:

Frontend: Change the check to evaluate the arguments array instead of the command string.

Change: as.config.command?.some(...)

To: as.config.args?.some(...)

Backend: In computer-use.mjs, instead of throwing a fatal error, gracefully return a safe dummy object (e.g., { command: "echo", args: [""] }) or properly handle the rejected promise so it doesn't crash the frontend data fetching.
