### PR TITLE
fix(app): type sonner CSS custom properties so tsc is clean

### PR DESCRIPTION
**Pull request by benjaminshafii**
`apps/app` typecheck was failing on `dev`. Green gate restored.

```
src/components/ui/sonner.tsx(42,9): error TS2353: Object literal may only specify known properties,
and '"--normal-bg"' does not exist in type 'Properties<string | number, string & {}>'.
```

It only reproduces on a **fresh install** of unmodified `dev`, not against stale `node_modules` — which is why it went unnoticed, and why I initially misattributed it to an unrelated PR's dependency change.

## Fix

The style object is declared as `React.CSSProperties & Record<`--${string}`, string>`, so CSS custom properties are legal without a cast. No `as`, no `any`. Built-JS grep confirms all four custom properties and their values are unchanged.

| Command | Result |
| --- | --- |
| `tsc --noEmit` | exit 0, no output |
| `apps/app` suite | 528 pass / 0 fail |
| `build:web` | exit 0 |

### CODE REVIEW

**Comment by benjaminshafii** [comment]
Merging with `openwork-tests (macos-14)` red. That failure is **pre-existing on `dev`** and unrelated to this PR: it is `evals/packages/behaviors/test/probe-tls.test.ts:17` (`facts.tls12.ok` false on macos-14), introduced by #3304 (`00617cde0`) — the first red commit on `dev`. The identical failure occurs on a types-only PR in this batch, and `OpenWork Tests` was green at `1fd556911` before #3304 landed. Every other check is green and the package-level suites pass.
